### ISSUE TITLE
Ошибка нету атрибуты в right_actual_image.copy()

### ISSUE THREAD

**Issue by argenalmaz00** [ZernovTechno/AR_headset#9]
Всё установил правильно, но здесь ругается на отсутствие атрибутов
right_actual_image.copy() << здесь нужен атрибуты

Exception in thread right_eye:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/argenalmaz00/code/Python/AR_headset/AR_HeadSet.py", line 98, in work_right
    working_with = right_actual_image.copy()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by usiqwerty** [comment]
У вас почему-то right_actual_image содержит None, а не кадр с камеры

**Comment by Denatle** [comment]
камеру вторую не нашёл. Точно две подключено?

**Comment by argenalmaz00** [comment]
нет у меня нет 2й камера,я половина кода убрал на правые камера,но толка левые также остался ошибка с атрибуты
`working_with = left_actual_image.copy()`
случайно это не новые версия numpy ?

**Comment by usiqwerty** [comment]
У вас линукс, там нет DirectShow.
Попробуйте убрать в файле AR_headset.py все упоминания cv2.CAP_DSHOW (или поставить cv2.CAP_AUTO)

**Comment by zernovtechno** [comment]
Да, дело в DSHOW из за линукса. Но вообще, там есть режим для одной камеры, вверху можно выбрать use_1_camera
